from cython_gsl cimport *

cdef class PhysConst:
        string name 
        string linestyle
        string markerstyle
        string colorstyle
        string savefilename
        double pi
        double piby2; 
        double sqrt2
        double ln2
        double earthradius
        double sunradius
        double GF
        double Na
        double sw_sq
        double G
        double alpha
        double TeV
        double GeV
        double MeV
        double keV
        double Joule
        double kg
        double gr
        double sec
        double hour
        double day
        double year
        double meter
        double cm
        double km
        double fermi
        double angstrom
        double AU
        double parsec
        double picobarn
        double femtobarn
        double Pascal
        double hPascal
        double atm
        double psi
        double Kelvin
        double degree
        int numneu 
        int numneumax
        string neutype
        double th12
        double th13
        double th23
        double th14
        double th24
        double th34
        double th15
        double th25
        double th35
        double th45
        double th16
        double th26
        double th36
        double th46
        double th56
        double dm21sq
        double dm31sq
        double dm41sq
        double dm51sq
        double dm61sq
        double delta1
        double delta2
        double delta3
        gsl_matrix th
        gsl_matrix c
        gsl_matrix s
        gsl_matrix dcp
        gsl_matrix dmsq
        gsl_matrix_complex U
        int Refresh()
        PhysConst() except +